//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Enchantment) DeepCopyInto(out *Enchantment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Enchantment.
func (in *Enchantment) DeepCopy() *Enchantment {
	if in == nil {
		return nil
	}
	out := new(Enchantment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Enchantment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnchantmentList) DeepCopyInto(out *EnchantmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Enchantment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnchantmentList.
func (in *EnchantmentList) DeepCopy() *EnchantmentList {
	if in == nil {
		return nil
	}
	out := new(EnchantmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnchantmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnchantmentRetentionPolicy) DeepCopyInto(out *EnchantmentRetentionPolicy) {
	*out = *in
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnchantmentRetentionPolicy.
func (in *EnchantmentRetentionPolicy) DeepCopy() *EnchantmentRetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(EnchantmentRetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnchantmentSpec) DeepCopyInto(out *EnchantmentSpec) {
	*out = *in
	in.Retention.DeepCopyInto(&out.Retention)
	in.Artifact.DeepCopyInto(&out.Artifact)
	if in.SelfReport != nil {
		in, out := &in.SelfReport, &out.SelfReport
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnchantmentSpec.
func (in *EnchantmentSpec) DeepCopy() *EnchantmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnchantmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnchantmentSpecArtifact) DeepCopyInto(out *EnchantmentSpecArtifact) {
	*out = *in
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]EnchantmentSpecArtifactRequirement, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnchantmentSpecArtifact.
func (in *EnchantmentSpecArtifact) DeepCopy() *EnchantmentSpecArtifact {
	if in == nil {
		return nil
	}
	out := new(EnchantmentSpecArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnchantmentSpecArtifactRequirement) DeepCopyInto(out *EnchantmentSpecArtifactRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnchantmentSpecArtifactRequirement.
func (in *EnchantmentSpecArtifactRequirement) DeepCopy() *EnchantmentSpecArtifactRequirement {
	if in == nil {
		return nil
	}
	out := new(EnchantmentSpecArtifactRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnchantmentStatus) DeepCopyInto(out *EnchantmentStatus) {
	*out = *in
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnchantmentStatus.
func (in *EnchantmentStatus) DeepCopy() *EnchantmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnchantmentStatus)
	in.DeepCopyInto(out)
	return out
}
