apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "runesmith-backend.fullname" . }}
  labels:
    {{- include "runesmith-backend.fullname" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-500"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  configFile: |
    server:
      address: ""
      port: "{{ .Values.server.port }}"
      maxBodySizeMB: 25
      ginMode: "{{ .Values.server.ginMode }}"
      defaultRequestTimeout: 30s
    magicalItems: {{ toYaml .Values.magicalItems | nindent 4 }}