apiVersion: v1
kind: Service
metadata:
  name: {{ include "runesmith-backend.fullname" . }}
  labels:
    {{- include "runesmith-backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "runesmith-backend.selectorLabels" . | nindent 4 }}
