name: push-manawell.yml
run-name: Pushing manawell by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - 'components/manawell-device-plugin/**'
      - 'deployment/helm/manawell-device-plugin/**'
      - '.github/workflows/push-manawell.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'components/manawell-device-plugin/**'
      - 'deployment/helm/manawell-device-plugin/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Compute Base Version & Build Number
        id: compute-version
        run: |
          BASE_VERSION="$(cat ./components/manawell-device-plugin/.Version | tr -d '[:space:]')"
          BUILD_NUMBER="${{ github.run_number }}"
          FULL_VERSION="${BASE_VERSION}.${BUILD_NUMBER}"

          echo "base_version=$BASE_VERSION" >> "$GITHUB_OUTPUT"
          echo "build_number=$BUILD_NUMBER" >> "$GITHUB_OUTPUT"
          echo "full_version=$FULL_VERSION" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT2GHCR }}

      - name: Build and push Docker image for Manawell Device Plugin
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./components/manawell-device-plugin/Dockerfile
          build-args: |
            FULL_VERSION=${{ steps.compute-version.outputs.full_version }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/manawell-device-plugin:${{ steps.compute-version.outputs.full_version }}
            ghcr.io/${{ github.repository_owner }}/manawell-device-plugin:latest

      - name: Package chart
        env:
          CHART_VERSION: ${{ steps.compute-version.outputs.full_version }}
        run: |
          helm package ./deployment/helm/manawell-device-plugin \
            --version "$CHART_VERSION" \
            --app-version "$CHART_VERSION" \
            --destination ./chart-dist

      - name: Push chart to GHCR
        env:
          CHART_VERSION: ${{ steps.compute-version.outputs.full_version }}
          GHCR_REPO: ghcr.io/${{ github.repository_owner }}/helm
        run: |
          helm registry login ghcr.io \
            --username '${{ github.actor }}' \
            --password '${{ secrets.PAT2GHCR }}'

          helm push ./chart-dist/manawell-device-plugin-"$CHART_VERSION".tgz \
            oci://$GHCR_REPO