name: push-enchanter.yml
run-name: Pushing runesmith-enchanter by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - 'components/runesmith-enchanter/**'
      - '.github/workflows/runesmith-enchanter.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'components/runesmith-enchanter/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Compute Base Version & Build Number
        id: compute-version
        run: |
          BASE_VERSION="$(cat ./components/runesmith-enchanter/.Version | tr -d '[:space:]')"
          BUILD_NUMBER="${{ github.run_number }}"
          FULL_VERSION="${BASE_VERSION}.${BUILD_NUMBER}"

          echo "base_version=$BASE_VERSION" >> "$GITHUB_OUTPUT"
          echo "build_number=$BUILD_NUMBER" >> "$GITHUB_OUTPUT"
          echo "full_version=$FULL_VERSION" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT2GHCR }}

      - name: Build and push Docker image for Runesmith Enchanter
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./components/runesmith-enchanter/Dockerfile
          build-args: |
            FULL_VERSION=${{ steps.compute-version.outputs.full_version }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/runesmith-enchanter:${{ steps.compute-version.outputs.full_version }}
            ghcr.io/${{ github.repository_owner }}/runesmith-enchanter:latest